//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVC_CtlrUsingEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemployee
    {
        public string empid { get; set; }
        public string empname { get; set; }
        public System.DateTime empdob { get; set; }
        public Nullable<int> empage { get; set; }
        public string empmobile { get; set; }
        public Nullable<int> empdept { get; set; }
        public Nullable<int> salary { get; set; }
        public string empgender { get; set; }
        public string empPic { get; set; }
    }
}
