//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVC_CtlrUsingEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentDetail
    {
        public string studID { get; set; }
        public string studname { get; set; }
        public Nullable<int> studAge { get; set; }
        public string studMobile { get; set; }
        public string studGender { get; set; }
        public Nullable<int> studStatus { get; set; }
    }
}
